---
title: "Fourmile"
author: "Megan Sears"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    theme: journal
editor_options: 
  chunk_output_type: console
---

```{r open package, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 

library(rmdformats)
library(tidyverse)
library(dplyr)
library(lubridate)
library(plotly)
library(ggplot2)
library(here)
library(scales)
library(here)
library(rgdal)
library(sp)
library(sf)
library(mapview)
library(kableExtra)
library(dataRetrieval)
library(raster)
library(sf)
library(stringr)
library(hydroGOF)
library(Metrics)
library(ranger)
library(missRanger)
library(readxl)
library(Rainmaker)
```

## Calculating rainfall metrics for Bennett data

```{r}
setwd("N:/Research/Kampf/Private/field_data/bennett")

rain <- read_csv('bennett_all_rain.csv')
```

## We want the following metrics: 
-depth (mm); duration (hrs); 
-maximum intensity (mm h-1) over 5-, 15-, 30-, and 60-minute intervals (MI5, MI15, MI30 and MI60); 
-kinetic energy (MJ h-1 ); 
-and erosivity (EI30)

### Prep the data

```{r}
#prep the data for the Rainmaker functions - try on 1 site first

uw_rain <- rain %>%
  dplyr::select(c(datetime, site, precip_mm)) %>%
  filter(site == 'uw') %>%
  dplyr::select(-c(site)) %>%
  rename(pdate = datetime)

uw_rm <- RMprep(uw_rain, prep.type = 2, date.type = 2,
                tz = 'MST')
  

uw_events <- RMevents(uw_rm, ieHr = 6,
                      rainthresh = .254,
                      rain = 'precip_mm',
                      time = 'pdate')

events <- uw_events$storms2

ggplot(events, aes(x=rain)) +
  geom_histogram(binwidth = 1, color="black", fill="white")

#######################################
# rainfall intensity 
RMintensity <- function(df,date="r.date",rain = "rain",
                        df.events,sdate="StartDate",edate="EndDate",
                        depth="depth",
                        xmin=c(60,180,360)) {
  
  # Compute overall event intensity
  df.events$duration <- (as.numeric(difftime(df.events[,edate],
                                             df.events[,sdate],units="hours")))
  df.events$Ievent <- df.events[,depth]/df.events$duration
  
  # Determine x-minute intensities for each of the intensities specified  
  
  for (i in 1:length(xmin)){
    x <- xmin[i]*60
    intensity.var <- paste("I",xmin[i],sep="")
    df.events[,intensity.var] <- NA
    
    #   Isolate individual events and Compute max x-min intensity for each event 
    #   period: compute sum rain and divide by duration. Report x-min intensity 
    #   in units/hr
    
    for (j in 1:nrow(df.events)) {
      subdf <- df[which(df[,date] >= df.events[j,sdate] & df[,date] <= df.events[j,edate]),]
      # Initialize intensity vector
      intensity <- numeric(length=nrow(subdf))
      
      for (k in 1:nrow(subdf)){
        enddate <- subdf[k,date]+x
        bdate <- subdf[k,date]
        
        subdf2 <- subdf[which(subdf[,date] >= bdate & subdf[,date] < enddate),]
        intensity[k] <- sum(subdf2[,rain], na.rm = T)/(x/60/60)
        
        #      k;bdate;enddate;intensity[k];max(subdf2$rain)
      }
      df.events[j,intensity.var] <- max(intensity,na.rm=TRUE)
    }
  }
  
  return(df.events)
}

intens <- RMintensity(uw_rm, 
                      date = 'pdate',
                      rain = 'precip_mm',
                      events, 
                      sdate = "StartDate",
                      edate = 'EndDate', 
                      depth = 'rain', xmin = c(60))


# intensities <- RMintensity(RDB3,date="pdate",
# rain="upload.ph3_site_basin_cedar_creek.Id.0....Geographical.Mean.kg.m.2.",
# events.0.2,sdate="StartDate",edate="EndDate",depth="rain",xmin=c(5,15,30))




```

```{r}

install.packages("remotes")
remotes::install_gitlab("water/analysis-tools/Rainmaker",
                        host = "code.usgs.gov")

library(Rainmaker)


```

