---
title: "Bennett_dataprocessing"
author: "Megan Sears"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    theme: journal
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stringr)
library(lubridate)
library(plotly)
library(kableExtra)
library(here)
```


```{r loading data, include=FALSE}
setwd("N:/Research/Kampf/Private/field_data/bennett")

#load rainfall metric functions
load('rain_metrics.RData')

#pull in all filenames with composite
filenames <- list.files(".", pattern="composite", full.names=F)

#read all the csvs
dataframes <- lapply(filenames, read.csv)

#name all the csv
names(dataframes) <- substr(filenames, 1, 14)

#extract csvs from list to global env
lapply(names(dataframes), function(x) assign(x, dataframes[[x]], envir = .GlobalEnv))
rm(dataframes) #remove dataframes list

```

## Rainfall (via tipping buckets)

```{r initial processing, echo=FALSE}
#me rain
me_rain <- me_rain_compos %>%
  mutate(site = "me") %>%
  rename(datetime = 1) %>%
  mutate(datetime = parse_date_time(datetime, 
                                  orders = c('%m/%d/%Y %H:%M',
                                             '%m/%d/%y %I:%M:%S %p',
                                             '%m-%d-%y %H:%M',
                                             '%Y-%m-%d %H:%M')),
         precip_mm = 0.254) %>%
  filter(!between(datetime, as.POSIXct('2021-10-31 00:00:00', tz='MST'),
                                as.POSIXct('2022-05-05 00:00:00', tz='MST')))

rm(me_rain_compos)

#mm rain
mm_rain <- mm_rain_compos %>%
  mutate(site = "mm") %>%
  mutate(datetime = ymd_hm(datetime),
         precip_mm = 0.254) %>%
  filter(!between(datetime, as.POSIXct('2021-10-31 00:00:00', tz='MST'),
                                as.POSIXct('2022-05-05 00:00:00', tz='MST')))

rm(mm_rain_compos)
  
#mw rain
mw_rain <- mw_rain_compos %>%
  mutate(site = "mw") %>%
  mutate(datetime = parse_date_time(datetime, 
                                    orders = c('%m/%d/%Y %H:%M',
                                               '%Y-%m-%d %H:%M')),
         precip_mm = 0.254) %>%
  filter(!between(datetime, as.POSIXct('2021-10-31 00:00:00', tz='MST'),
                                as.POSIXct('2022-05-05 00:00:00', tz='MST')))
rm(mw_rain_compos)

#ue rain
ue_rain <- ue_rain_compos %>%
  mutate(site = "ue") %>%
  mutate(datetime = parse_date_time(datetime, 
                                    orders = c('%m/%d/%Y %H:%M',
                                               '%m/%d/%y %I:%M:%S %p',
                                               '%Y-%m-%d %H:%M')),
         precip_mm = 0.254) %>%
  filter(!between(datetime, as.POSIXct('2021-10-31 00:00:00', tz='MST'),
                                as.POSIXct('2022-05-05 00:00:00', tz='MST')))

rm(ue_rain_compos)

#um rain
um_rain <- um_rain_compos %>%
  mutate(site = "um") %>%
  mutate(datetime = mdy_hm(datetime),
         precip_mm = 0.254) %>%
  filter(!between(datetime, as.POSIXct('2021-10-31 00:00:00', tz='MST'),
                                as.POSIXct('2022-05-05 00:00:00', tz='MST')))

rm(um_rain_compos)

#uw rain
uw_rain <- uw_rain_compos %>%
  mutate(site = "uw") %>%
  mutate(datetime = parse_date_time(datetime, 
                                    orders = c('%m/%d/%Y %H:%M',
                                               '%Y-%m-%d %H:%M')),
         precip_mm = 0.254) %>%
  filter(!between(datetime, as.POSIXct('2021-10-31 00:00:00', tz='MST'),
                                as.POSIXct('2022-05-05 00:00:00', tz='MST')))
  
rm(uw_rain_compos)
  
#bind all rain data together
rain <- bind_rows(me_rain, mm_rain, mw_rain, ue_rain, um_rain, uw_rain)

rain_daily <- rain %>%
  mutate(date = date(datetime)) %>%
  group_by(site, date) %>%
  summarize(dailyp_mm = sum(precip_mm)) 

rain_plot <- ggplot(rain_daily, aes(x=date, y=dailyp_mm, color=site)) +
  geom_point() + 
  ylim(0,50)

ggplotly(rain_plot)

## need to write to csv so can be used to determine rainfall metrics
#write.csv(rain, 'bennett_all_rain.csv')
#write.csv(rain_daily, 'rain_daily.csv')

```

### Rainfall metrics

```{r rainfall metrics, echo=FALSE}
# REMOVE THE FILTER P<1 and do it before summarizing below
get_events <- function(df, event, P_mm, datenumeric, end, start) {
  df_event=group_by(df,event) %>%
    summarize(P=sum(P_mm, na.rm=T),start=min(datenumeric),
              end=max(datenumeric),duration=end-start)
  df_event$duration_hr=df_event$duration/60/60
  
  #df_event <- df_event %>% filter(P > 1)
  
  return(df_event)
}


#me 
me_rain <- get_setup(me_rain, me_rain$datetime)
me_events <- get_events(me_rain, me_rain$P_mm, me_rain$datenumeric,
                        me_rain$end, me$rain_start)
me_events <- get_intensities(me_events, me_events$event, me_rain)

#write_csv(me_events, 'me_rain_events.csv')
#me_events <- read_csv('me_rain_events.csv')

#mm
#use gap fill mm_rain (gap filled with me)
mm_rain <- read_csv("mm_rain_gapfill.csv") %>%
  mutate(datetime = ymd_hm(datetime))

mm_rain <- get_setup(mm_rain, mm_rain$datetime)
mm_events <- get_events(mm_rain, mm_rain$P_mm, mm_rain$datenumeric,
                       mm_rain$end, mm$rain_start)

mm_events <- get_intensities(mm_events, mm_events$event, mm_rain)

# write_csv(mm_events, 'mm_rain_events.csv')
# mm_events <- read_csv('mm_rain_events.csv')

#mw
mw_rain <- get_setup(mw_rain, mw_rain$datetime)
mw_events <- get_events(mw_rain, mw_rain$P_mm, mw_rain$datenumeric,
                        mw_rain$end, mw$rain_start)
mw_events <- get_intensities(mw_events, mw_events$event, mw_rain)

# write_csv(mw_events, 'mw_rain_events.csv')
# mw_events <- read_csv('mw_rain_events.csv')

#ue
ue_rain <- get_setup(ue_rain, ue_rain$datetime)
ue_events <- get_events(ue_rain, ue_rain$P_mm, ue_rain$datenumeric,
                        ue_rain$end, ue$rain_start)
ue_events <- get_intensities(ue_events, ue_events$event, ue_rain)

# write_csv(ue_events, 'ue_rain_events.csv')
# ue_events <- read_csv('ue_rain_events.csv')

#um -- use uw since there is no um data
um_rain <- get_setup(um_rain, um_rain$datetime)
um_events <- get_events(um_rain, um_rain$P_mm, um_rain$datenumeric,
                       um_rain$end, um$rain_start)
um_events <- get_intensities(um_events, um_events$event, um_rain)

# write_csv(um_events, 'um_rain_events.csv')
# um_events <- read_csv('um_rain_events.csv')

#uw
uw_rain <- get_setup(uw_rain, uw_rain$datetime)
uw_events <- get_events(uw_rain, uw_rain$P_mm, uw_rain$datenumeric,
                        uw_rain$end, uw$rain_start)
uw_events <- get_intensities(uw_events, uw_events$event, uw_rain)

# # write_csv(uw_events, 'uw_rain_events.csv')
#uw_events <- read_csv('uw_rain_events.csv')

#add site id to each events df 
me_events <- me_events %>% 
  mutate(Site = 'me') %>%
  filter(P > 1)

mm_events <- mm_events %>% 
  mutate(Site = 'mm') %>%
  filter(P > 1)

mw_events <- mw_events %>% 
  mutate(Site = 'mw') %>%
  filter(P > 1)

ue_events <- ue_events %>% 
  mutate(Site = 'ue') %>%
  filter(P > 1)

um_events <- um_events %>% 
  mutate(Site = 'um') %>%
  filter(P > 1)

uw_events <- uw_events %>% 
  mutate(Site = 'uw') %>%
  filter(P > 1)

#bind event dfs together
event_list <- list(me_events, mm_events, mw_events,
                   ue_events, um_events, uw_events)

#all events for all sites
events <- bind_rows(event_list)

events <- events %>% filter(P > 1)

ggplot(events, aes(x=Site, y=P)) + geom_boxplot() +
  ggtitle('Precip per event (mm)')

ggplot(events, aes(x=Site, y=duration_hr)) + geom_boxplot() +
  ggtitle('Event duration (hr)')

ggplot(events, aes(x=Site, y=MI60)) + geom_boxplot() +
  ggtitle('MI60')

ggplot(events, aes(x=Site, y=MI30)) + geom_boxplot() +
  ggtitle('MI30')

ggplot(events, aes(x=Site, y=MI15)) + geom_boxplot() +
  ggtitle('MI15')

ggplot(events, aes(x=Site, y=MI5)) + geom_boxplot()+
  ggtitle('MI5')

events_summary <- events %>%
  select(c(Site, P, MI60, MI30, MI15, MI5)) %>%
  group_by(Site) %>%
  summarize(Count = n(),
            Total_P = sum(P, na.rm = TRUE),
            Median_P = median(P, na.rm = TRUE),
            Max_P = max(P, na.rm = TRUE),
            Stdev_P = sd(P, na.rm = TRUE),
            Max_MI60 = max(MI60, na.rm = TRUE),
            Stdev_MI60 = sd(MI60, na.rm = TRUE),
            Max_MI30 = max(MI30, na.rm = TRUE),
            Stdev_MI30 = sd(MI30, na.rm = TRUE),
            Max_MI15 = max(MI15, na.rm = TRUE),
            Stdev_MI15 = sd(MI15, na.rm = TRUE),
            Max_MI5 = max(MI5, na.rm = TRUE),
            Stdev_MI5 = sd(MI5, na.rm = TRUE)) %>%
  mutate_if(is.numeric,
            round,
            digits = 4)

kable(events_summary) %>%
  kable_styling()

```

## Stream stage

```{r process stage data, echo=FALSE}

#me stage
me_stage <- me_stage_compo %>%
  mutate(site = 'me',
         datetime = parse_date_time(datetime, 
                                    orders = c('%m/%d/%Y %H:%M',
                                               '%m-%d-%Y %H:%M:%S')))
rm(me_stage_compo)

#me_upper stage
me_upper_stage <- me_upper_stage %>%
  mutate(site = 'me_upper',
         datetime = mdy_hms(datetime))

#mm stage
mm_stage <- mm_stage_compo %>%
  mutate(site = 'mm',
         datetime = parse_date_time(datetime, 
                                    orders = c('%m/%d/%Y %H:%M',
                                               '%m/%d/%Y %H:%M:%S')))
rm(mm_stage_compo)

#mm upper stage
mm_upper_stage <- mm_upper_stage %>%
  mutate(site = 'mm_upper',
         datetime = mdy_hms(datetime))

#mw stage
mw_stage <- mw_stage_compo %>%
  mutate(site = 'mw',
         datetime = parse_date_time(datetime, 
                                    orders = c('%m/%d/%Y %H:%M',
                                               '%m/%d/%Y %H:%M:%S')))
rm(mw_stage_compo)

#mw_upper stage
mw_upper_stage <- mw_upper_stage %>%
  mutate(site = 'mw_upper',
         datetime = mdy_hms(datetime))

#ue stage
ue_stage <- ue_stage_compo %>%
  mutate(site = 'ue',
         datetime = parse_date_time(datetime, 
                                    orders = c('%m/%d/%Y %H:%M',
                                               '%m/%d/%Y %H:%M:%S')))
rm(ue_stage_compo)

#ue_upper stage (not downloaded yet)
ue_upper_stage <- ue_upper_stage %>%
  mutate(site = 'ue_upper',
         datetime = mdy_hms(datetime))

#um stage
um_stage <- um_stage_compo %>%
  mutate(site = 'um',
         datetime = parse_date_time(datetime, 
                                    orders = c('%m/%d/%Y %H:%M',
                                               '%m/%d/%Y %H:%M:%S')))

rm(um_stage_compo)

#um_lower stage
um_lower_stage <- um_lower_stage %>%
  mutate(site = 'um_lower',
         datetime = parse_date_time(datetime, 
                                    orders = c('%m/%d/%Y %H:%M',
                                               '%m/%d/%Y %H:%M:%S')))
#uw stage
uw_stage <- uw_stage_compo %>%
  mutate(site = 'uw',
         datetime = parse_date_time(datetime, 
                                    orders = c('%m/%d/%Y %H:%M',
                                               '%m-%d-%Y %H:%M:%S')))

rm(uw_stage_compo)

#uw_upper stage
uw_upper_stage <- uw_upper_stage %>%
  mutate(site = 'uw_upper',
         datetime = mdy_hms(datetime))

stage <- bind_rows(me_stage, me_upper_stage, mm_stage, mm_upper_stage,
                   mw_stage, mw_upper_stage, ue_stage, ue_upper_stage, um_stage, um_lower_stage,
                   uw_stage, uw_upper_stage)

stage_plot <- ggplot(stage, aes(x=datetime, y=Stage_mm, color=site)) +
  geom_line()

ggplotly(stage_plot)

#write.csv(stage, 'bennett_stage.csv')


```

## Stage response to rainfall

```{r stage response, echo = FALSE}

#get stage response for each site
me_response <- get_stageresponse(me_events, me_stage)
mm_response <- get_stageresponse(mm_events, mm_stage)
mw_response <- get_stageresponse(mw_events, mw_stage)
ue_response <- get_stageresponse(ue_events, ue_stage)
um_response <- get_stageresponse(um_events, um_stage)
uw_response <- get_stageresponse(uw_events, uw_stage)

response_list <- list(me_response, mm_response, mw_response,
                   ue_response, um_response, uw_response)

#all events for all sites
response <- bind_rows(response_list)

ggplot(response, aes(x=site, y=Stage_range)) + geom_boxplot() +
  ggtitle('Stage response amount (mm)')

ggplot(response, aes(x=site, y=lag2p_hr)) + geom_boxplot() +
  ggtitle('Lag to Peak (hr)')

ggplot(response, aes(x=site, y=Stage_mm_max)) + geom_boxplot() +
  ggtitle('Stage max (mm)')

ggplot(response, aes(x=MI60, y=lag2p_hr, color = site)) + geom_point() +
  ggtitle('MI60 vs lag to peak')

ggplot(response, aes(x=MI60, y=Stage_range, color = site)) + geom_point() +
  ggtitle('MI60 vs stage max')

response_summary <- response %>%
  ungroup() %>% 
  select(c(site, Stage_mm_max, Stage_range, lag2p_hr, response)) %>%
  group_by(site) %>%
  summarize(Count = n(),
            Positive_response = sum(response),
            Median_Stage_response = median(Stage_range),
            Mean_Stage_response = mean(Stage_range),
            Stdev_Stage_response = sd(Stage_range),
            Median_lag2p_hr = median(lag2p_hr),
            Mean_lag2p_hr = mean(lag2p_hr),
            Stdev_lag2p_hr = sd(lag2p_hr)) %>%
  mutate_if(is.numeric,
            round,
            digits = 2)

ggplot(response_summary, aes(x=site, y=(Positive_response/Count))) + 
  geom_col() +
  ggtitle('Percent of response (response to events/total events)')

kable(response_summary) %>%
  kable_styling()


```

## Rainfall thresholds

```{r rainfall thresholds, echo = FALSE}

# thresholds=data.frame(seq(0, 30, by = 0.1))
# 
# #identify threshold for one site
# site=me_response
# site=filter(site,!is.na(site$Stage))
# site=filter(site,!is.na(site$MI60))
# num=32
# 
# #flow_pred is the threshold prediction of flow for MI15, 30, 60
# #correct indicatese whether the threshold prediction is correct
# flow_pred_15=data.frame(matrix(0, ncol = num, nrow = 301))  
# flow_pred_30=data.frame(matrix(0, ncol = num, nrow = 301))  
# flow_pred_60=data.frame(matrix(0, ncol = num, nrow = 301))  
# correct_15=data.frame(matrix(0, ncol = num, nrow = 301))  
# correct_30=data.frame(matrix(0, ncol = num, nrow = 301))  
# correct_60=data.frame(matrix(0, ncol = num, nrow = 301))  
# 
# for(j in seq(from=1, to=num, by=1)){
#   for(i in seq(from=1, to=301, by=1)){
#     flow_pred_15[i,j]=ifelse(site[j,5]>thresholds[i,1],1,0)
#     flow_pred_30[i,j]=ifelse(site[j,6]>thresholds[i,1],1,0)
#     flow_pred_60[i,j]=ifelse(site[j,7]>thresholds[i,1],1,0)
#     correct_15[i,j]=ifelse(flow_pred_15[i,j]==site[j,8],1,0)
#     correct_30[i,j]=ifelse(flow_pred_30[i,j]==site[j,8],1,0)
#     correct_60[i,j]=ifelse(flow_pred_60[i,j]==site[j,8],1,0)
#   }
# }
# 
# #computes fraction correct for each threshold value; also computes kappa stat
# p0_15=data.frame(matrix(0, ncol = 1, nrow = 301))
# p0_30=data.frame(matrix(0, ncol = 1, nrow = 301))
# p0_60=data.frame(matrix(0, ncol = 1, nrow = 301))
# pflow_obs=sum(site[c(1:num),8])/num
# pnoflow_obs=1-pflow_obs
# pflow_15=data.frame(matrix(0, ncol = 1, nrow = 301))
# pflow_30=data.frame(matrix(0, ncol = 1, nrow = 301))
# pflow_60=data.frame(matrix(0, ncol = 1, nrow = 301))
# pnoflow_15=data.frame(matrix(0, ncol = 1, nrow = 301))
# pnoflow_30=data.frame(matrix(0, ncol = 1, nrow = 301))
# pnoflow_60=data.frame(matrix(0, ncol = 1, nrow = 301))
# pe_15=data.frame(matrix(0, ncol = 1, nrow = 301))
# pe_30=data.frame(matrix(0, ncol = 1, nrow = 301))
# pe_60=data.frame(matrix(0, ncol = 1, nrow = 301))
# kappa_15=data.frame(matrix(0, ncol = 1, nrow = 301))
# kappa_30=data.frame(matrix(0, ncol = 1, nrow = 301))
# kappa_60=data.frame(matrix(0, ncol = 1, nrow = 301))
# 
# for(i in seq(from=1, to=301, by=1)){
#   p0_15[i,1]=sum(correct_15[i,c(1:num)])/num
#   p0_30[i,1]=sum(correct_30[i,c(1:num)])/num
#   p0_60[i,1]=sum(correct_60[i,c(1:num)])/num
#   pflow_15[i,1]=sum(flow_pred_15[i,c(1:num)])/num
#   pflow_30[i,1]=sum(flow_pred_30[i,c(1:num)])/num
#   pflow_60[i,1]=sum(flow_pred_60[i,c(1:num)])/num
#   pnoflow_15[i,1]=1-pflow_15[i,1]
#   pnoflow_30[i,1]=1-pflow_30[i,1]
#   pnoflow_60[i,1]=1-pflow_60[i,1]
#   pe_15[i,1]=pflow_obs*pflow_15[i,1]+pnoflow_obs*pnoflow_15[i,1]
#   pe_30[i,1]=pflow_obs*pflow_30[i,1]+pnoflow_obs*pnoflow_30[i,1]
#   pe_60[i,1]=pflow_obs*pflow_60[i,1]+pnoflow_obs*pnoflow_60[i,1]
#   kappa_15[i,1]=(p0_15[i,1]-pe_15[i,1])/(1-pe_15[i,1])
#   kappa_30[i,1]=(p0_30[i,1]-pe_30[i,1])/(1-pe_30[i,1])
#   kappa_60[i,1]=(p0_60[i,1]-pe_60[i,1])/(1-pe_60[i,1])
# }  


```

## Larimer County Bennett precip and Q

```{r larimer co rainfall metrics, echo = FALSE}
#how to get rainfall metrics when it is hourly
# ben_rain <- read_csv(here('./bennett/larimerco_bennett_precip.csv')) %>%
#   mutate(datetime = ymd_hm(DateTime)) %>%
#   mutate(precip_mm = precip_in*25.4) %>%
#   filter(datetime > '2021-06-21 00:00') %>%
#   filter(!between(datetime, as.POSIXct('2021-10-31 00:00', tz='MST'),
#                                 as.POSIXct('2022-05-05 00:00', tz='MST')))
# 
#   
# 
# 
# ben_rain <- get_setup(ben_rain, ben_rain$datetime)
# 
# ben_events <- get_events(ben_rain, ben_rain$P_mm, ben_rain$datenumeric,
#                         ben_rain$end, ben_rain$rain_start)
# 
# 
# ue_events <- get_intensities(ue_events, ue_events$event, ben_rain)



```

```{r}


get_stageresponse2 <- function(events_df, stage_df) {
  
  response <- data.frame()
  
  for(i in 1:nrow(events_df)){
    temp <- stage_df %>%
      filter(datetime >=(events_df$starttime[i]) 
             & datetime <=(events_df$endtime[i] + 12*60*60))
    
    temp$event = ifelse(temp$datetime >=(events_df$starttime[i]) 
                        & temp$datetime <=(events_df$endtime[i] + 12*60*60),
                        events_df$event[i])
    
    temp$duration_hr = ifelse(temp$datetime >=(events_df$starttime[i]) 
                              & temp$datetime <=(events_df$endtime[i] + 12*60*60),
                              events_df$duration_hr[i])
    
    temp$P = ifelse(temp$datetime >=(events_df$starttime[i]) 
                    & temp$datetime <=(events_df$endtime[i] + 12*60*60),
                    events_df$P[i])
    
    temp$MI5 = ifelse(temp$datetime >=(events_df$starttime[i]) 
                      & temp$datetime <=(events_df$endtime[i] + 12*60*60),
                      events_df$MI5[i])
    
    temp$MI15 = ifelse(temp$datetime >=(events_df$starttime[i]) 
                       & temp$datetime <=(events_df$endtime[i] + 12*60*60),
                       events_df$MI15[i])
    
    temp$MI30 = ifelse(temp$datetime >=(events_df$starttime[i]) 
                       & temp$datetime <=(events_df$endtime[i] + 12*60*60),
                       events_df$MI30[i])
    
    temp$MI60 = ifelse(temp$datetime >=(events_df$starttime[i]) 
                       & temp$datetime <=(events_df$endtime[i] + 12*60*60),
                       events_df$MI60[i])
    
    temp$starttime = ifelse(temp$datetime >=(events_df$starttime[i]) 
                            & temp$datetime <=(events_df$endtime[i] + 12*60*60),
                            events_df$starttime[i])
    
    temp$endtime = ifelse(temp$datetime >=(events_df$starttime[i]) 
                          & temp$datetime <=(events_df$endtime[i] + 12*60*60),
                          events_df$endtime[i])
    
    response <- rbind(response, temp)
  }
  
  out <- response %>%
    group_by(event) %>%
    mutate(Stage_range = max(Stage_mm) - min(Stage_mm)) %>%
    group_by(event) %>%
    filter(Stage_mm == max(Stage_mm)) %>%
    rename(Stage_mm_max = Stage_mm) %>% 
    group_by(event) %>%
    filter(datetime == max(datetime)) %>%
    rename(datetime_maxstage = datetime) %>%
    mutate(starttime_rain = as_datetime(starttime),
           endtime_rain = as_datetime(endtime),
           lag2p_hr = as.numeric(datetime_maxstage - starttime_rain)) %>%
    filter(!duration_hr == 0) %>%
    mutate(response = ifelse(Stage_range > 2, 1, 0)) %>% 
    select(-c(starttime, endtime))
  
}


me_response <- get_stageresponse2(me_events, me_stage)
mm_response <- get_stageresponse2(mm_events, mm_stage)
mw_response <- get_stageresponse2(mw_events, mw_stage)
ue_response <- get_stageresponse2(ue_events, ue_stage)
um_response <- get_stageresponse2(uw_events, um_stage)
uw_response <- get_stageresponse2(uw_events, uw_stage)

response_list <- list(me_response, mm_response, mw_response,
                   ue_response, um_response, uw_response)

#all events for all sites
response <- bind_rows(response_list)

response_summary <- response %>%
  ungroup() %>% 
  select(c(site, Stage_mm_max, Stage_range, lag2p_hr, response)) %>%
  group_by(site) %>%
  summarize(Count = n(),
            Positive_response = sum(response),
            Max_Stage_Response = max(Stage_range),
            Median_Stage_response = median(Stage_range),
            Mean_Stage_response = mean(Stage_range),
            Stdev_Stage_response = sd(Stage_range),
            Median_lag2p_hr = median(lag2p_hr),
            Mean_lag2p_hr = mean(lag2p_hr),
            Stdev_lag2p_hr = sd(lag2p_hr)) %>%
  mutate_if(is.numeric,
            round,
            digits = 2)


```