---
title: "CPF_all_processing"
author: "Megan Sears"
date: '2022-08-24'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r load packages, incldue = F}

library(tidyverse)
library(plotly)
library(lubridate)
library(stringr)
library(knitr)

knitr::opts_knit$set(root.dir = 'N:/Research/Kampf/Private/field_data')

```


```{r load in data, include = F}
setwd('N:/Research/Kampf/Private/field_data')

#pull in all filenames with composite
filenames <- list.files(".", pattern="composite", full.names=F)

#read all the csvs
dataframes <- lapply(filenames, read.csv)

#name all the csv
names(dataframes) <- substr(filenames, 1, 25)

#extract csvs from list to global env
lapply(names(dataframes), function(x) assign(x, dataframes[[x]], envir = .GlobalEnv))

# remove old 'dataframes' and remove andrews site
rm(dataframes, Andrews_rain_composite.cs, Andrews_sm_composite.csv) #remove dataframes list

#pull in Bighorn composite data
setwd("N:/Research/Kampf/Private/field_data/bighorn")
filenames2 <- list.files(".", pattern="composite.", full.names=F)

#do same steps as above
#read all the csvs
dataframes2 <- lapply(filenames2, read.csv)

#name all the csv
names(dataframes2) <- substr(filenames2, 1, 25)

#extract csvs from list to global env
lapply(names(dataframes2), function(x) assign(x, dataframes2[[x]], envir = .GlobalEnv))
rm(dataframes2)

#pull in Dry Creek composite data
setwd("N:/Research/Kampf/Private/field_data/dry_creek")
filenames3 <- list.files(".", pattern="composite.", full.names=F)

#do same steps as above
#read all the csvs
dataframes3 <- lapply(filenames3, read.csv)

#name all the csv
names(dataframes3) <- substr(filenames3, 1, 25)

#extract csvs from list to global env
lapply(names(dataframes3), function(x) assign(x, dataframes3[[x]], envir = .GlobalEnv))
rm(dataframes3)

#set wd back
setwd('N:/Research/Kampf/Private/field_data')

```

## Rain and precip

```{r rain and precip}
#aspen tipping bucket
aspen_rain <- Aspen_rain_composite.csv %>%
    mutate(datetime = parse_date_time(date_time, 
                                  orders = c('%m/%d/%Y %H:%M',
                                             '%y-%m-%d %H:%M')),
           tips = 1,
           date = date(datetime)) %>%
  group_by(date) %>%
  summarize(rain_mm_daily = sum(tips)*0.3)

rm(Aspen_rain_composite.csv)

#bighorn tipping bucket
bighorn_rain <- bighorn_rain_composite_ne %>%
  mutate(datetime = parse_date_time(datetime, 
                                  orders = c('%m/%d/%Y %H:%M',
                                             '%y-%m-%d %H:%M')),
         date = date(datetime)) %>%
  group_by(date) %>% 
  summarize(rain_mm_daily = sum(tips)*0.1)

rm(bighorn_rain_composite_ne)

#bl4 tipping bucket
bl4_rain <- bl4_rain_composite.csv %>%
  mutate(datetime = parse_date_time(datetime, 
                                  orders = c('%m/%d/%Y %H:%M',
                                             '%y-%m-%d %H:%M')),
           tips = 1,
           date = date(datetime)) %>%
  group_by(date) %>%
  summarize(rain_mm_daily = sum(tips)*0.3)

rm(bl4_rain_composite.csv)
  
#dry creek tipping bucket - powered through a met station until May 2022
dry_rain <- dry_rain_composite_new.cs %>%
  mutate(datetime = parse_date_time(DateTime, 
                                  orders = c('%m/%d/%Y %H:%M',
                                             '%y-%m-%d %H:%M')),
         date = date(datetime)) %>%
  group_by(date) %>%
  summarize(rain_mm_daily = sum(tips)*0.1)

rm(dry_rain_composite_new.cs)

#greyrock tipping bucket (removed in May 2022)
greyrock_rain <- Greyrock_rain_composite.c %>%
  mutate(datetime = parse_date_time(date_time, 
                                  orders = c('%m/%d/%Y %H:%M',
                                             '%y-%m-%d %H:%M',
                                             '%m/%d/%y %I:%M:%S %p')),
         date = date(datetime),
         tips = 1) %>%
  group_by(date) %>% 
  summarize(rain_mm_daily = sum(tips)*0.3)
  
rm(Greyrock_rain_composite.c)

#joe wright tipping bucket - powered through a met station
joewright_rain <- joewright_rain_composite. %>%
  mutate(datetime = parse_date_time(DateTime, 
                                  orders = c('%m/%d/%Y %H:%M',
                                             '%y-%m-%d %H:%M')),
         date = date(datetime)) %>%
  group_by(date) %>%
  summarize(rain_mm_daily = sum(tips)*0.1)

rm(joewright_rain_composite.)

#montgomery tipping bucket
montgomery_rain <- montgomery_rain_composite %>%
  mutate(datetime = parse_date_time(DateTime, 
                                  orders = c('%m/%d/%Y %H:%M',
                                             '%y-%m-%d %H:%M')),
           tips = 1,
           date = date(datetime)) %>%
    group_by(date) %>% 
  summarize(rain_mm_daily = sum(tips)*0.3)
  
rm(montgomery_rain_composite)

#skin tipping bucket
skin_rain <- Skin_rain_composite.csv %>%
  mutate(datetime = parse_date_time(date_time, 
                                  orders = c('%m/%d/%Y %H:%M',
                                             '%y-%m-%d %H:%M')),
           date = date(datetime),
         tips = 1) %>%
    group_by(date) %>% 
  summarize(rain_mm_daily = sum(tips)*0.3)

rm(Skin_rain_composite.csv)

#tunnel tipping bucket - powered through a met station
tunnel_rain <- tunnel_rain_composite.csv %>%
  mutate(datetime = parse_date_time(DateTime, 
                                  orders = c('%m/%d/%Y %H:%M',
                                             '%y-%m-%d %H:%M')),
         date = date(datetime)) %>%
  group_by(date) %>%
  summarize(rain_mm_daily = sum(tips)*0.1)

rm(tunnel_rain_composite.csv)

#dry creek geonor
dry_geonor <- dry_geonor_composite.csv %>%
  mutate(depth_avg_mm = round(depth_avg_mm, digits = 2),
    precip_mm  = if_else((depth_avg_mm - lag(depth_avg_mm)) < 0.05,
                              0,
                              (depth_avg_mm - lag(depth_avg_mm))),
    date = date(datetime)) %>%
  group_by(date) %>%
  summarize(precip_mm_daily = sum(precip_mm))

rm(dry_geonor_composite.csv)

#tunnel geonor
tunnel_geonor <- tunnel_geonor_composite.c %>%
  mutate(depth_avg_mm = round(depth_avg_mm, digits = 2),
    precip_mm  = if_else((depth_avg_mm - lag(depth_avg_mm)) < 0.05,
                              0,
                              (depth_avg_mm - lag(depth_avg_mm))),
    date = date(datetime)) %>%
  group_by(date) %>%
  summarize(precip_mm_daily = sum(precip_mm))

rm(tunnel_geonor_composite.c)

#output all rain and precip daily data
write_csv(aspen_rain, 'Aspen_P_daily.csv')
write_csv(bighorn_rain, './bighorn/Bighorn_P_daily_new.csv')
write_csv(bl4_rain, 'bl4_P_daily.csv')
write_csv(dry_rain, './dry_creek/Dry_P_daily_new.csv')
write_csv(greyrock_rain, 'Greyrock_P_daily.csv')
write_csv(joewright_rain, 'joewright_P_daily.csv')
write_csv(montgomery_rain, 'montgomery_P_daily.csv')
write_csv(skin_rain, 'Skin_P_daily.csv')
write_csv(tunnel_rain, 'tunnel_P_daily.csv')
write_csv(dry_geonor, './dry_creek/Dry_geonor_daily.csv')
write_csv(tunnel_geonor, 'Tunnel_geonor_daily.csv')


#output daily WY rain and precip data (WY2022 next)
#add site to each df, then bindrows, and filter dates

```

## Met data

### Bighorn met data

```{r met}

#update all this code later

bighorn_met=read_csv('./bighorn/bighorn_met_composite.csv')
bighorn_met <- bighorn_met %>%
mutate(datetime = parse_date_time(datetime, 
                                  orders = c('%m/%d/%Y %H:%M',
                                             '%y-%m-%d %H:%M')))
#bighorn_met$datetime = as_datetime(bighorn_met$datetime,tz="MST", format="%m/%d/%Y %H:%M")
bighorn_met$datetime = as.POSIXct(bighorn_met$datetime,tz="GMT",format="%m/%d/%Y %H")
bighorn_met$date=date(bighorn_met$datetime)

bighorn_met$Ta_C_old=(bighorn_met$Ta_F-32)*5/9
bighorn_met$RH_frac=bighorn_met$RH_percent/100

bighorn_met_daily=group_by(bighorn_met,date) %>%
  summarize(Ta_C=mean(Ta_C),Ta_C_old=mean(Ta_C_old),Ts_5=mean(Ts_5),Ts_20=mean(Ts_20),Ts_50=mean(Ts_50),
            SM_5=mean(VWC_5)/100,SM_20=mean(VWC_20)/100,
            SM_50=mean(VWC_50)/100,Rn=mean(Rn_Wm2),SnowD_cm=mean(SnowD_m)*100,RH=mean(RH_frac),
            u_ms=mean(u_ms),Rs_in=mean(Rs_in),Rs_out=mean(Rs_out),Rl_in=mean(Rl_in),
            Rl_out=mean(Rl_out),Rn=mean(Rn),albedo=mean(albedo))

#bighorn_met$VWC_20_test=bighorn_met$VWC_20*(-1)-11
bighorn_sm=ggplot()+geom_line(data=bighorn_met,aes(x=datetime,y=VWC_5),color='red')+
  geom_line(data=bighorn_met,aes(x=datetime,y=VWC_20),color='orange')+
  geom_line(data=bighorn_met,aes(x=datetime,y=VWC_50),color='blue')
ggplotly(bighorn_sm)


bighorn_Rs=ggplot()+geom_line(data=bighorn_met,aes(x=datetime,y=Rs_in))+
  geom_line(data=bighorn_met,aes(x=datetime,y=Rs_out),color='red')+
  geom_line(data=bighorn_met,aes(x=datetime,y=Rn),color='blue')
ggplotly(bighorn_Rs)

bighorn_Rl=ggplot()+geom_line(data=bighorn_met,aes(x=datetime,y=Rl_in))+
  geom_line(data=bighorn_met,aes(x=datetime,y=Rl_out),color='red')
ggplotly(bighorn_Rl)

bighorn_T=ggplot()+geom_line(data=bighorn_met,aes(x=datetime,y=Ts_5),color='red')+
  geom_line(data=bighorn_met,aes(x=datetime,y=Ts_20),color='orange')+
  geom_line(data=bighorn_met,aes(x=datetime,y=Ts_50),color='blue')+
  geom_line(data=bighorn_met,aes(x=datetime,y=Ta_C),color='black')
ggplotly(bighorn_T)

bighorn_snow=ggplot()+geom_line(data=bighorn_met,aes(x=datetime,y=SnowD_m))
ggplotly(bighorn_snow)

bighorn_RH=ggplot()+geom_line(data=bighorn_met,aes(x=datetime,y=RH_percent))
ggplotly(bighorn_RH)

bighorn_u=ggplot()+geom_line(data=bighorn_met,aes(x=datetime,y=u_ms))
ggplotly(bighorn_u)

write_csv(bighorn_met_daily, 'bighorn_met_daily.csv')

```

### Dry Creek met data

```{r dry creek met data}
dry_met=read_csv('./dry_creek/dry_met_composite.csv')
dry_met <- dry_met %>%
  mutate(datetime = parse_date_time(DateTime, 
                                  orders = c('%m/%d/%Y %H:%M',
                                             '%y-%m-%d %H:%M')))

dry_met$datetime = as.POSIXct(dry_met$datetime,tz="GMT",format="%m/%d/%Y %H")
dry_met$date=date(dry_met$datetime)

dry_met$VWC_20=ifelse(dry_met$VWC_20<0.08,NA,dry_met$VWC_20)
dry_met$VWC_50=ifelse(dry_met$VWC_50<0.08,NA,dry_met$VWC_50)

dry_met_daily=group_by(dry_met,date) %>%
  summarize(Ta_C=mean(Ta_C,na.rm=T),Ts_C=mean(Ts_C,na.rm=T),SM_5=mean(VWC_5),SM_20=mean(VWC_20),
            SM_50=mean(VWC_50),Rn=mean(Rn_Wm2),SnowD_cm=mean(SnowD_m)*100,RH=mean(RH_frac),
            u_ms=mean(u_ms))

dry_sm=ggplot()+geom_line(data=dry_met_daily,aes(x=date,y=SM_5),color='red')+
  geom_line(data=dry_met_daily,aes(x=date,y=SM_20),color='orange')+
  geom_line(data=dry_met_daily,aes(x=date,y=SM_50),color='blue')
ggplotly(dry_sm)

dry_Rn=ggplot()+geom_line(data=dry_met_daily,aes(x=date,y=Rn))
ggplotly(dry_Rn)

dry_T=ggplot()+geom_line(data=dry_met_daily,aes(x=date,y=Ts_C))+
  geom_line(data=dry_met_daily,aes(x=date,y=Ta_C),color='blue')
ggplotly(dry_T)

dry_snow=ggplot()+geom_line(data=dry_met_daily,aes(x=date,y=SnowD_cm))
ggplotly(dry_snow)

dry_RH=ggplot()+geom_line(data=dry_met_daily,aes(x=date,y=RH))
ggplotly(dry_RH)

dry_u=ggplot()+geom_line(data=dry_met_daily,aes(x=date,y=u_ms))
ggplotly(dry_u)

write_csv(dry_met_daily,'dry_met_daily.csv')

```

### Joe Wright met station

```{r}
joewright_met=read_csv('joewright_met_composite.csv')

joewright_met <- joewright_met %>%
  mutate(datetime = parse_date_time(datetime, 
                                  orders = c('%m/%d/%Y %H:%M',
                                             '%y-%m-%d %H:%M')))

#joewright_met$datetime = as_datetime(joewright_met$datetime,tz="MST", format="%m/%d/%Y %H:%M")
joewright_met$datetime = as.POSIXct(joewright_met$datetime,tz="GMT",format="%m/%d/%Y %H")
joewright_met$date=date(joewright_met$datetime)

joewright_met_daily=group_by(joewright_met,date) %>%
  summarize(Ta_C=mean(Ta_C),Ts_C=mean(Ts_C),SM_5=mean(VWC_5),SM_20=mean(VWC_20),
            SM_50=mean(VWC_50),Rs_in=mean(Rs_in_Wm2),Rs_out=mean(Rs_out_Wm2),Rl_in=mean(Rl_in_Wm2),
            Rl_out=mean(Rl_out_Wm2),albedo=mean(albedo),Rn=mean(Rn_Wm2),RH=mean(RH_percent)/100,
            u_ms=mean(u_ms))

jw_sm=ggplot()+geom_line(data=joewright_met,aes(x=datetime,y=VWC_5),color='red')+
  geom_line(data=joewright_met,aes(x=datetime,y=VWC_20),color='orange')+
  geom_line(data=joewright_met,aes(x=datetime,y=VWC_50),color='blue')
ggplotly(jw_sm)

jw_Rs=ggplot()+geom_line(data=joewright_met,aes(x=datetime,y=Rs_in_Wm2))+
  geom_line(data=joewright_met,aes(x=datetime,y=Rs_out_Wm2),color='orange')
ggplotly(jw_Rs)

jw_Rl=ggplot()+geom_line(data=joewright_met,aes(x=datetime,y=Rl_in_Wm2))+
  geom_line(data=joewright_met,aes(x=datetime,y=Rl_out_Wm2),color='orange')+
  geom_line(data=joewright_met,aes(x=datetime,y=Rn_Wm2),color='blue')
ggplotly(jw_Rl)

jw_T=ggplot()+geom_line(data=joewright_met,aes(x=datetime,y=Ts_C))+
  geom_line(data=joewright_met,aes(x=datetime,y=Ta_C),color='blue')
ggplotly(jw_T)

jw_RH=ggplot()+geom_line(data=joewright_met,aes(x=datetime,y=RH_percent))
ggplotly(jw_RH)

jw_u=ggplot()+geom_line(data=joewright_met,aes(x=datetime,y=u_ms))
ggplotly(jw_u)

write_csv(joewright_met_daily,'joewright_met_daily.csv')


```


### Joe Wright burn met station

```{r}

```


### Tunnel met station

```{r}
tunnel_met=read_csv('tunnel_met_composite.csv')

tunnel_met <- tunnel_met %>%
  mutate(datetime = parse_date_time(DateTime, 
                                  orders = c('%m/%d/%Y %H:%M',
                                             '%y-%m-%d %H:%M')))

#tunnel_met$datetime = as_datetime(tunnel_met$DateTime,tz="MST", format="%m/%d/%Y %H:%M")
tunnel_met$datetime = as.POSIXct(tunnel_met$datetime,tz="GMT",format="%m/%d/%Y %H")
tunnel_met$date=date(tunnel_met$datetime)

tunnel_met$Depth_cm=tunnel_met$Depth_m*100

tunnel_met_daily=group_by(tunnel_met,date) %>%
  summarize(Ta_C=mean(Ta_C),Ts_C=mean(Ts_C),SM_5=mean(VWC_5),SM_20=mean(VWC_20),
            SM_50=mean(VWC_50),Rs_in=mean(Rs_in),Rs_out=mean(Rs_out),Rl_in=mean(Rl_in),
            Rl_out=mean(Rl_out),albedo=mean(albedo),Rn_NRlite=mean(Rn_Wm2),RH=mean(RH)/100,
            u_ms=mean(u_ms))

tunnel_sm=ggplot()+geom_line(data=tunnel_met,aes(x=datetime,y=VWC_5),color='red')+
  geom_line(data=tunnel_met,aes(x=datetime,y=VWC_20),color='orange')+
  geom_line(data=tunnel_met,aes(x=datetime,y=VWC_50),color='blue')
ggplotly(tunnel_sm)

tunnel_Rs=ggplot()+geom_line(data=tunnel_met,aes(x=datetime,y=Rs_in))+
  geom_line(data=tunnel_met,aes(x=datetime,y=Rs_out),color='orange')
ggplotly(tunnel_Rs)
#there are times when out is greater than in

tunnel_Rl=ggplot()+geom_line(data=tunnel_met,aes(x=datetime,y=Rl_in))+
  geom_line(data=tunnel_met,aes(x=datetime,y=Rl_out),color='orange')+
  geom_line(data=tunnel_met,aes(x=datetime,y=Rn_Wm2),color='blue')
ggplotly(tunnel_Rl)
#no 4 comp radiometer 7/21 to 9/21

tunnel_T=ggplot()+geom_line(data=tunnel_met,aes(x=datetime,y=Ts_C))+
  geom_line(data=tunnel_met,aes(x=datetime,y=Ta_C),color='blue')
ggplotly(tunnel_T)

tunnel_RH=ggplot()+geom_line(data=tunnel_met,aes(x=datetime,y=RH))
ggplotly(tunnel_RH)

tunnel_u=ggplot()+geom_line(data=tunnel_met,aes(x=datetime,y=u_ms))
ggplotly(tunnel_u)

tunnel_snow=ggplot()+geom_line(data=tunnel_met,aes(x=datetime,y=Depth_cm))
ggplotly(tunnel_snow)
#needs to be offset adjusted for 0 snow depth

write_csv(tunnel_met_daily,'tunnel_met_daily.csv')

```

### Mt Campus met station

```{r}

```

## Stream stage and stream flow

```{r}

```

