---
title: "Bennett stage"
author: "Megan Sears"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_float: yes
    theme: journal
editor_options:
  chunk_output_type: console
---

```{r setup, include = F}
knitr::opts_chunk$set(
  echo = F,
  message = F, 
  warning  = F)

library(tidyverse)
library(lubridate)
library(plotly)
library(kableExtra)
library(here)
library(ggplot2); theme_set(theme_bw(base_size = 16))

```

```{r, fig.width=12, fig.height=10}

#washout larimer co
washout_larimer <- read_csv('washout_stage_larimerco.csv') %>%
  select(datetime = DateTime,
         stage_ft = `WaterLevelRiver(11525007)`) %>%
  mutate(datetime = mdy_hm(datetime),
         stage_cm_larimer = stage_ft*30.48) %>%
  select(-stage_ft)

## PT
#washout
washout_stage_pt <- read_csv('/Volumes/Kampf/Private/field_data/washout_stage_composite.csv') %>%
  mutate(DateTime = mdy_hm(DateTime))


washout_stage_pt$Date = as_date(washout_stage_pt$DateTime,tz="GMT")
#washout_stage_pt$DateTime = as_datetime(washout_stage_pt$DateTime,tz="GMT", format="%m/%d/%Y %H:%M")
washout_stage_pt$hour=hour(washout_stage_pt$DateTime)
washout_stage_hourly=group_by(washout_stage_pt,Date,hour) %>%
  summarize(Pw_kPa=mean(P_kPa))
washout_stage_hourly$DateTime=as.POSIXct(paste(washout_stage_hourly$Date, washout_stage_hourly$hour), format="%Y-%m-%d %H")

# dry baro
Dry_baro=read_csv('/Volumes/Kampf/Private/field_data/dry_creek/Dry_baro_composite.csv')
Dry_baro$Date = as_date(Dry_baro$datetime,tz="GMT", format="%m/%d/%Y %H:%M")
Dry_baro$DateTime = as_datetime(Dry_baro$datetime,tz="GMT", format="%m/%d/%Y %H:%M")
Dry_baro$hour=hour(Dry_baro$DateTime)
Dry_baro_hourly=group_by(Dry_baro,Date,hour) %>%
  summarize(Pa_psi=mean(Pa_psi))
Dry_baro_hourly$DateTime=as.POSIXct(paste(Dry_baro_hourly$Date, Dry_baro_hourly$hour), format="%Y-%m-%d %H")

Dry_baro_hourly <- Dry_baro_hourly %>%
  drop_na(DateTime)


washout_stage_hourly=full_join(washout_stage_hourly,Dry_baro_hourly,by="DateTime")
washout_stage_hourly$Pa_kPa=washout_stage_hourly$Pa_psi*6.89476
washout_stage_hourly$Stage_kPa=washout_stage_hourly$Pw_kPa-washout_stage_hourly$Pa_kPa
washout_stage_hourly$Stage_mm=washout_stage_hourly$Stage_kPa*101.97162129779
washout_stage_hourly$DateTime2=as.character(washout_stage_hourly$DateTime)

washout_stage_hourly <- washout_stage_hourly %>%
  filter(DateTime > "2021-02-22 00:00:00")

#convert stage from sensor units to cm
washout_stage_hourly$Stage_cm=washout_stage_hourly$Stage_mm/10


#goal is to offset-adjust sensor stage to levels of manual stage
#this example does the bulk offset adjustment
washout_stage_hourly$Stage_corr_cm = washout_stage_hourly$Stage_cm
washout_stage_hourly$Stage_corr_cm=washout_stage_hourly$Stage_cm+9.4

#this example offset-adjusts at a download date where the sensor level changed from 
#before to after download
washout_stage_hourly$Stage_corr_cm=ifelse(washout_stage_hourly$DateTime>'2021-04-08 12:00:00',
                                          washout_stage_hourly$Stage_corr_cm-5,washout_stage_hourly$Stage_corr_cm)

#4/19-20, scouring. move stage up
washout_stage_hourly$Stage_corr_cm=ifelse(washout_stage_hourly$DateTime>'2021-04-20 01:00:00',
                                          washout_stage_hourly$Stage_corr_cm+6,washout_stage_hourly$Stage_corr_cm)
#4/29, slight data download offset
washout_stage_hourly$Stage_corr_cm=ifelse(washout_stage_hourly$DateTime>'2021-04-29 23:00:00',
                                          washout_stage_hourly$Stage_corr_cm-1,washout_stage_hourly$Stage_corr_cm)

#6/26, bed aggrades. move stage down
washout_stage_hourly$Stage_corr_cm=ifelse(washout_stage_hourly$DateTime>'2021-06-25 15:00:00',
                                          washout_stage_hourly$Stage_corr_cm-1,washout_stage_hourly$Stage_corr_cm)

washout_stage_hourly$Stage_corr_cm=ifelse(washout_stage_hourly$DateTime>'2021-07-12 15:00:00',
                                          washout_stage_hourly$Stage_corr_cm-3,washout_stage_hourly$Stage_corr_cm)

#7/20, bed aggrades. move stage down
washout_stage_hourly$Stage_corr_cm=ifelse(washout_stage_hourly$DateTime>'2021-07-20 15:00:00',
                                          washout_stage_hourly$Stage_corr_cm-1,washout_stage_hourly$Stage_corr_cm)

#7/30, bed incises. move stage up
washout_stage_hourly$Stage_corr_cm=ifelse(washout_stage_hourly$DateTime>'2021-07-31 05:00:00',
                                          washout_stage_hourly$Stage_corr_cm+3,washout_stage_hourly$Stage_corr_cm)


washout_pt <- washout_stage_hourly %>%
  select(datetime = DateTime, pt_stage = Stage_corr_cm)

washout_comp <- left_join(washout_pt, washout_larimer, by = 'datetime') %>%
  pivot_longer(!datetime, names_to = 'site', values_to = 'stage_cm')

compare <- ggplot(washout_comp,
       aes(datetime, stage_cm,
           color = site)) +
  geom_line()

ggplotly(compare)

washout_1_1 <- left_join(washout_pt, washout_larimer, by = 'datetime') %>%
  drop_na()

compare2 <- ggplot(washout_1_1,
       aes(x = pt_stage, y = stage_cm_larimer)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1, size=1, color='red') +
  expand_limits(x = 0, y = 0) +
  ggtitle('1:1 for PT stage vs. Larimer stage')

ggplotly(compare2)

```

