---
title: "Snow surveys 2021 to 2023"
author: "Megan Sears"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(
  echo = F,
  message = F, 
  warning  = F)

# load packages
library(tidyverse)
library(lubridate)
library(ggplot2); theme_set(theme_bw(base_size = 16))
library(here)

```

# Read in data

```{r}

ss_2021 <- read_csv(here('snow_surveys/data/snow_survey_2021.csv'))

ss_2022 <- read_csv(here('snow_surveys/data/survey_2022_all.csv'))

ss_2023 <- read_csv(here('snow_surveys/data/survey_2023_all.csv'))

coords <- read_csv(here('snow_surveys/data/geode_master_2022.csv')) %>%
  select(id = Name, aspect, burn_use) %>% #remove the lat long for now
  mutate(aspect_dir = case_when(
    between(aspect, 0, 22.5) ~"North",
    between(aspect, 22.5, 67.5) ~ "Northeast",
    between(aspect, 67.5, 112.5) ~ "East",
    between(aspect, 112.5, 157.5) ~ "Southeast",
    between(aspect, 157.5, 202.5) ~ "South",
    between(aspect, 202.5, 247.5) ~ "Southwest",
    between(aspect, 247.5, 292.5) ~ "West",
    between(aspect, 292.5, 337.5) ~ "Northwest",
    between(aspect, 337.5, 360) ~ "North"),
    id = toupper(id))

```

# Process/clean data

```{r}

# set up 2022
ss2022 <- ss_2022 %>%
  mutate(datetime = mdy_hm(`Date and Time`)) %>%
  mutate(date = as.Date(datetime)) %>%
  select(-c(1:6, 10:11, 24:27)) %>%
  rename(transect = `Transect Name`,
         id = `Point ID`,
         burn = `Burn status`,
         depth1_cm = `Depth 1 (cm)`,
         depth2_cm = `Depth 2 (cm)`,
         depth3_cm = `Depth 3 (cm)`,
         depth4_cm = `Depth 4 (cm)`,
         depth5_cm = `Depth 5 (cm)`,
         diam_cm = `Snow core diameter (cm)`,
         coredepth1_cm = `Snow core 1 depth (cm)`,
         coreweight1_g = `Snow core 1 weight (g)`,
         coredepth2_cm = `Snow core 2 depth (cm)`,
         coreweight2_g = `Snow core 2 weight (g)`,
         coredepth3_cm = `Snow core 3 depth (cm)`,
         coreweight3_g = `Snow core 3 weight (g)`) %>%
  mutate(month = month(date),
         id = toupper(id)) %>%
  left_join(., coords, by = 'id') %>%
  mutate(year = '2022')

# set up 2023
ss2023 <- ss_2023 %>%
    mutate(datetime = mdy_hm(`Date and Time`)) %>%
  mutate(date = as.Date(datetime)) %>%
  select(-c(1:6, 10:11, 24:27)) %>%
  rename(transect = `Transect Name`,
         id = `Point ID`,
         burn = `Burn status`,
         depth1_cm = `Depth 1 (cm)`,
         depth2_cm = `Depth 2 (cm)`,
         depth3_cm = `Depth 3 (cm)`,
         depth4_cm = `Depth 4 (cm)`,
         depth5_cm = `Depth 5 (cm)`,
         diam_cm = `Snow core diameter (cm)`,
         coredepth1_cm = `Snow core 1 depth (cm)`,
         coreweight1_g = `Snow core 1 weight (g)`,
         coredepth2_cm = `Snow core 2 depth (cm)`,
         coreweight2_g = `Snow core 2 weight (g)`,
         coredepth3_cm = `Snow core 3 depth (cm)`,
         coreweight3_g = `Snow core 3 weight (g)`) %>%
  mutate(month = month(date),
         id = toupper(id)) %>%
  left_join(., coords, by = 'id') %>% 
  mutate(coreweight3_g = as.numeric(coreweight3_g),
         year = '2023')
  
# snow survey 2021 - let match to 2022 and 2023
ss2021_coords <- ss_2021 %>%
  mutate(id = toupper(ID)) %>%
  select(id, aspect, burn_use = burn_sev, transect = Transect) %>%
  distinct(id, .keep_all = T) %>%
  mutate(transect = case_when(
    grepl("PB_T", transect) ~ "Transitional_burn",
    grepl("UB_T", transect) ~ "Transitional_unburn",
    grepl("B_T", transect) ~ "Transitional_burn",
    grepl("B_P", transect) ~ "Persistent",
    grepl("UB_P", transect) ~ "Persistent",
    grepl("PB_P", transect) ~ "Persistent"))
  


ss2021 <- ss_2021 %>% 
  mutate(id = toupper(ID)) %>% 
  select(id, depth_mean, swe_mean, month = Month) %>%
  left_join(., ss2021_coords, by = 'id') %>%
  mutate(year = '2021') %>%
  mutate(aspect_dir = case_when(
    between(aspect, 0, 22.5) ~"North",
    between(aspect, 22.5, 67.5) ~ "Northeast",
    between(aspect, 67.5, 112.5) ~ "East",
    between(aspect, 112.5, 157.5) ~ "Southeast",
    between(aspect, 157.5, 202.5) ~ "South",
    between(aspect, 202.5, 247.5) ~ "Southwest",
    between(aspect, 247.5, 292.5) ~ "West",
    between(aspect, 292.5, 337.5) ~ "Northwest",
    between(aspect, 337.5, 360) ~ "North"))

#add 2022 and 2023 together to get mean depth and swe before adding 2021
second2 <- bind_rows(ss2022, ss2023) %>%
  group_by(id, month, year) %>%
  mutate(depth_mean = mean(c(depth1_cm,
                           depth2_cm,
                           depth3_cm,
                           depth4_cm,
                           depth5_cm),
                           na.rm = T),
         avg_weight_g = mean(c(coreweight1_g,
                             coreweight2_g,
                             coreweight3_g)),
         avg_cordepth_cm = mean(c(coredepth1_cm,
                                coredepth2_cm,
                                coredepth3_cm))) %>%
  mutate(vol = pi*(6.25/2)^2*avg_cordepth_cm,
         dens = avg_weight_g / vol,
         swe = dens * avg_cordepth_cm) %>%
  select(swe_mean = swe, id, depth_mean, month, aspect, burn_use, year, transect, aspect_dir)

all <- bind_rows(ss2021, second2)

```

# box plots!

```{r}

all_twocats <- all %>%
  filter(!burn_use == '2') %>%
  mutate(burn = if_else(burn_use == '1', 'unburned',
                        'burned'))

persistent <- all_twocats %>%
  filter(transect == 'Persistent') %>% 
  ggplot(., aes(as.factor(month), depth_mean, fill = burn)) +
  geom_boxplot() +
  scale_fill_manual(values=c("#F7340B", 'darkgreen')) +
  #ggtitle('Persistent') +
  labs(x = "Month", y = 'Mean snow depth (cm)') +
  theme(legend.title=element_blank()) +
  theme(legend.position="bottom",
        text = element_text(size=28)) +
    theme(legend.title=element_blank()) +
  theme(legend.position="bottom",
        text = element_text(size=36, 
                            family = 'Times New Roman')) +
  facet_wrap(~as.factor(year))

persistent

ggsave(here('snow_surveys/figs/persistent_3years.jpg'), persistent, dpi=800)

trans <- all_twocats %>%
  filter(transect %in% c('Transitional_burn', 'Transitional_unburn')) %>% 
  ggplot(., aes(as.factor(month), depth_mean, fill = burn)) +
  geom_boxplot() +
  scale_fill_manual(values=c("#F7340B", 'darkgreen')) +
  #ggtitle('Transitional') +
  labs(x = "Month", y = 'Mean snow depth (cm)') +
  theme(legend.title=element_blank()) +
  theme(legend.position="bottom",
        text = element_text(size=28)) +
    theme(legend.title=element_blank()) +
  theme(legend.position="bottom",
        text = element_text(size=36, 
                            family = 'Times New Roman')) +
  facet_wrap(~as.factor(year))

trans

ggsave(here('snow_surveys/figs/trans_3years.jpg'), trans, dpi=800)

```

